write(">")
local input = read()
local request = http.get("https://raw.githubusercontent.com/CrimboJimbo/MinecraftDadBot/refs/heads/main/Text%20Test.txt")
local inputMod = string.gsub(input, " ", "_")
local txt = request.readAll()
local a,b = string.find(txt,inputMod)
print(string.sub(txt,a,b))
request.close()